webtalk_init -webtalk_dir C:/Users/ulyzk/Downloads/feature-calculation-template/sp3_linebuffer/sp3_linebuffer.sim/sim_1/behav/xsim/xsim.dir/line_buffer_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 22 18:56:08 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210806966_1777511497_210720380_308" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "625f552c-33f8-4cc2-a6ac-f8ebe2470331" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8e002a1a71c047d5aea6443424e39423" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "188" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows Server 2012 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 7702P 64-Core Processor               " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "76.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7104_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1195339845 -regid "210806966_1777511497_210720380_308" -xml C:/Users/ulyzk/Downloads/feature-calculation-template/sp3_linebuffer/sp3_linebuffer.sim/sim_1/behav/xsim/xsim.dir/line_buffer_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ulyzk/Downloads/feature-calculation-template/sp3_linebuffer/sp3_linebuffer.sim/sim_1/behav/xsim/xsim.dir/line_buffer_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ulyzk/Downloads/feature-calculation-template/sp3_linebuffer/sp3_linebuffer.sim/sim_1/behav/xsim/xsim.dir/line_buffer_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
